Updated the check for whether or not 'createdb' runs successfully.  This changed in 8.3.0.  'createdb' now silently runs successfuly.  Code for the previous version of PostgreSQL has been commented out.  Should be integrated back in so older versions of PostgreSQL can still be tested.

diff --git a/scripts/pgsql/create_db.sh.in b/scripts/pgsql/create_db.sh.in
--- a/scripts/pgsql/create_db.sh.in
+++ b/scripts/pgsql/create_db.sh.in
@@ -53,11 +53,16 @@ fi
 @TOPDIR@/scripts/pgsql/start_db.sh -o ${OUTPUT_DIR} -p "$PARAMETERS" || exit 1
 
 echo "Creating database $SID..."
-_o=`@CREATEDB@ -p ${DBPORT} $SID 2>&1`
-_test=`echo $_o | grep CREATE`
-if [ "$_test" = "" ]; then
-	echo "@CREATEDB@ -p ${DBPORT} $SID failed: $_o $_test"
-	exit 1
-fi
+# Prior to 8.3 we attempted to capture 'CREATE' from the output of the
+# 'createdb' command to determine the the command was successful.  We might
+# have to make a version check to determine the best way to determine whether
+# the command was successful or not.
+#_o=`@CREATEDB@ -p ${DBPORT} $SID 2>&1`
+#_test=`echo $_o | grep CREATE`
+#if [ "$_test" = "" ]; then
+#	echo "@CREATEDB@ -p ${DBPORT} $SID failed: $_o $_test"
+#	exit 1
+#fi
+@CREATEDB@ -p ${DBPORT} $SID 2>&1 || exit 1
 
 exit 0
