fix synchronization of refresh streams

diff --git a/scripts/pgsql/run_rf1.sh.in b/scripts/pgsql/run_rf1.sh.in
--- a/scripts/pgsql/run_rf1.sh.in
+++ b/scripts/pgsql/run_rf1.sh.in
@@ -20,10 +20,13 @@ DBPORT=$3
 
 PSQL="@PSQL@ -h ${HOSTNAME} -p ${DBPORT} -d ${SID}"
 
-curr_set_file_rf1="$RUNDIR/curr_set_num_rf1"
-lock_file_rf1="$RUNDIR/rf1.lock"
-min_set_file="$RUNDIR/min_set_num"
-max_set_file="$RUNDIR/max_set_num"
+SYNCFILEDIR=$RUNDIR/../../sync
+mkdir -p $SYNCFILEDIR
+
+curr_set_file_rf1="$SYNCFILEDIR/curr_set_num_rf1"
+lock_file_rf1="$SYNCFILEDIR/rf1.lock"
+min_set_file="$SYNCFILEDIR/min_set_num"
+max_set_file="$SYNCFILEDIR/max_set_num"
 
 # if curr_set_file does not exist, we generate 12 update sets
 # create a semaphore file so that only one process can access
@@ -59,36 +62,36 @@ then
 fi
 rm -f $lock_file_rf1
 
+# clean up if exists
+${PSQL} -c "drop table tmp_lineitem$set_num;"
+${PSQL} -c "drop table tmp_orders$set_num;"
+
 # generating the load .sql
-echo "COPY tmp_lineitem$set_num FROM '/tmp/lineitem.tbl.u$set_num' USING DELIMITERS '|';" >> tmp_lineitem$set_num.sql
-echo "COPY tmp_orders$set_num FROM '/tmp/orders.tbl.u$set_num' USING DELIMITERS '|';" >> tmp_orders$set_num.sql
+TMP_LINEITEM="COPY tmp_lineitem$set_num FROM '/tmp/lineitem.tbl.u$set_num' USING DELIMITERS '|';"
+TMP_ORDERS="COPY tmp_orders$set_num FROM '/tmp/orders.tbl.u$set_num' USING DELIMITERS '|';"
 
 echo "`date`: Stream ${set_num} : Starting Refresh Stream 1..."
 s_time=`$GTIME`
 
 ${PSQL} -c "create table tmp_lineitem$set_num (l_orderkey numeric(10), l_partkey numeric(10), l_suppkey numeric(10), l_linenumber numeric(10), l_quantity numeric(12,2), l_extendedprice numeric(12,2), l_discount numeric(12,2), l_tax numeric(12,2), l_returnflag char(1), l_linestatus char(1), l_shipdate date, l_commitdate date, l_receiptdate date, l_shipinstruct char(25), l_shipmode char(10), l_comment varchar(44));" || exit 1
 
-${PSQL} -f tmp_lineitem$set_num.sql || exit 1
+${PSQL} -c "${TMP_LINEITEM}" || exit 1
 
 ${PSQL} -c "insert into lineitem (select * from tmp_lineitem$set_num);" || exit 1
 
 ${PSQL} -c "create table tmp_orders$set_num (o_orderkey numeric(10), o_custkey numeric(10), o_orderstatus char(1), o_totalprice numeric(12,2), o_orderdate date, o_orderpriority char(15), o_clerk char(15), o_shippriority numeric(10), o_comment varchar(79));" || exit 1
 
-${PSQL} -f tmp_orders$set_num.sql || exit 1
+${PSQL} -c "${TMP_ORDERS}" || exit 1
 
 ${PSQL} -c "insert into orders (select * from tmp_orders$set_num);" || exit 1
 
 # clean up
 ${PSQL} -c "drop table tmp_lineitem$set_num;" || exit 1
-
 ${PSQL} -c "drop table tmp_orders$set_num;" || exit 1
 
 e_time=`$GTIME`
 echo "`date`: Stream ${set_num} : Refresh Stream 1 completed."
 let "diff_time=$e_time-$s_time"
 echo "Stream ${set_num} : Elapsed time for Refresh Stream 1 : $diff_time seconds"
-
-rm -f tmp_lineitem$set_num.sql
-rm -f tmp_orders$set_num.sql
 
 exit 0
